development:
  adapter: postgresql
  encoding: unicode
  database: netblp_development
test:
  adapter: postgresql
  encoding: unicode
  database: netblp_test
production:
  adapter: postgresql
  encoding: unicode
  database: netblp
